FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow==2.9.2 psycopg2-binary boto3

CMD mlflow server \
    --host 0.0.0.0 \
    --port 5001 \
    --backend-store-uri postgresql+psycopg2://mlflow:mlflow@mlflow-db:5432/mlflow \
    --default-artifact-root s3://mlflow-artifacts/ \
    --serve-artifacts
