version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.9.2
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/opt/airflow/backend
      - ./logs:/opt/airflow/logs 
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/backend/dags   
    entrypoint: /bin/bash
    command:
      - -c
      - |
        sleep 10  # wait for postgres to be ready
        airflow db init
        airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true
        airflow webserver & airflow scheduler

volumes:
  postgres-db-volume:
