services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=us-east-1
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_FORCE_PATH_STYLE=true
    depends_on:
      mlflow-db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - airflow
    restart: unless-stopped


  mlflow-db:
    image: postgres:16-alpine
    #platform: linux/arm64
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - mlflow-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'mlflow']
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - airflow
      - default
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    #platform: linux/arm64
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow
      - default
    restart: unless-stopped

  minio-mc:
    image: minio/mc:latest
    #platform: linux/arm64
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set localminio http://minio:9000 minioadmin minioadmin &&
      mc mb localminio/mlflow-artifacts || true &&
      true
      "
    networks:
      - airflow
      - default

networks:
  airflow:
    external: true
    name: sales-ai_e0abfd_airflow
  default:
    name: sales-ai_e0abfd_default

volumes:
  mlflow-db-volume:
  minio-data:
