data_paths:
  calendar: data/raw/calendar.csv
  features_data: data/features/m5/m5_features.parquet
  prices: data/raw/sell_prices.csv
  processed_data: data/processed/m5/m5_master.parquet
  sales_train: data/raw/sales_train_evaluation.csv
metadata:
  name: M5_Walmart_Dataset
  version: 1.0.0
processing:
  chunk_size: 5000
  max_memory_gb: 4.0
quality:
  max_zero_days_pct: 0.95
  min_sales_per_item: 100
