dataset:
  date_column: date
  group_columns:
  - store_id
  - item_id
  target_column: sales
date_features:
  basic_features:
  - year
  - month
  - day
  - dayofweek
  - quarter
  - weekofyear
  derived_features:
  - is_weekend
  - is_month_start
  - is_month_end
  enabled: true
  holiday_features:
    country: US
    enabled: true
lag_features:
  enabled: true
  sales_lags:
    dtype: int16
    windows:
    - 1
    - 2
    - 3
    - 7
    - 14
    - 21
    - 28
metadata:
  description: Default M5 feature engineering configuration
  name: M5_Walmart_Features
  version: 1.0.0
processing:
  chunk_size: 100000
  memory_efficient: true
  n_jobs: -1
rolling_features:
  enabled: true
  statistics:
  - dtype: float32
    name: mean
  - dtype: float32
    fill_na: 0
    name: std
  windows:
  - 7
  - 14
  - 28
