# Synthetic Data Compatibility
synthetic_data:
  schema:
    required_columns:
      - date
      - store_id
      - item_id
      - sales
      - promotion
      - price
      - holiday
      - weather_temp
      - weather_precip
    date_format: "%Y-%m-%d"
  source: data/synthetic/
  holiday_dates_path: data/external/holidays/holidays.csv
  country: "US"

# Feature Engineering
features:
  date_features:
    enabled: true
    cols: ["year", "month", "day", "dayofweek", "quarter", "weekofyear", "is_weekend", "is_holiday"]
  
  lag_features:
    enabled: true
    lags: [1, 2, 3, 7, 14, 21, 30]  # includes your original [1, 7, 14, 28]

  rolling_features:
    enabled: true
    windows: [3, 7, 14, 21, 30]     # includes original [7, 30, 90] if needed, add 90
    functions: ["mean", "std", "min", "max", "median"]

  cyclical_features:
    enabled: true                  # handles seasonality via sine/cosine transforms

  interaction_features:
    enabled: false                 # can turn on later to explore interaction terms

  ewm_features:
    enabled: false
    spans: [7, 14, 30]

  trend_features:
    enabled: false                 # optional, can infer trend via differencing

  ratio_features:
    enabled: false                 # e.g., sales-to-price, promo-to-sales

  feature_selection:
    enabled: true
    method: "random_forest"
    top_n: 50

# Grouping logic for lags/rollings
grouping:
  group_cols: ['store_id', 'item_id']
  exclude_cols: []  # you can populate with e.g., 'price' or others if needed

# Holiday Configuration
holiday:
  enabled: true
  country: "US"
  file: data/external/holidays/holidays.csv

# Data Validation
validation:
  required_columns:
    - "date"
    - "sales"
    - "store_id"
    - "item_id"
  data_types:
    date: "datetime64[ns]"
    sales: "float64"
    store_id: "object"
    item_id: "object"
  value_ranges:
    sales:
      min: 0
      max: 1000000

# Training Configuration
training:
  test_size: 0.2
  validation_size: 0.1
  cv_folds: 5
  metrics:
    - "rmse"
    - "mae"
    - "mape"
    - "r2"

# Inference Configuration
inference:
  batch_size: 1000
  prediction_horizon: 30     # days ahead
  confidence_intervals: [0.8, 0.95]

# Monitoring Configuration
monitoring:
  drift_detection:
    enabled: true
    method: "kolmogorov_smirnov"
    threshold: 0.1
  
  performance_monitoring:
    enabled: true
    alert_threshold:
      rmse: 1000
      mape: 0.2
