# config/m5_dataset_config.yaml

# Data paths
sales_train_path: "data/raw/sales_train_evaluation.csv"
prices_path: "data/raw/sell_prices.csv"
calendar_path: "data/raw/calendar.csv"

# Schema definitions (optional, can be null or omitted if you don't use)
sales_schema: null
prices_schema: null
calendar_schema: null

# Processing parameters
chunk_size: 5000
max_memory_gb: 8.0

# Validation thresholds
min_sales_per_item: 100
max_zero_days_pct: 0.95

# Output configuration
save_interim: true
save_features: true
compression: "snappy"
