validation:
  required_columns:
    - "date"
    - "sales"
    - "store_id"
    - "product_id"

  data_types:
    date: "datetime64[ns]"
    sales: "float64"
    store_id: "object"
    product_id: "object"

  value_ranges:
    sales:
      min: 0
      max: 1000000
  check_duplicates: true

  outlier_method: zscore  # options: zscore, iqr
